FROM amd64/python:3.7-slim-buster

RUN apt-get update && apt-get install -y --no-install-recommends libglib2.0-bin

WORKDIR /app

RUN pip install --upgrade pip

COPY ./app/requirements.txt ./
RUN pip install -r requirements.txt

COPY ./app/ .

# Expose the port
EXPOSE 80

# Run the flask server for the endpoints
CMD [ "python3", "-u", "./app.py" ]