FROM balenalib/raspberrypi3-debian-python:3.7

RUN [ "cross-build-start" ]

RUN apt update && apt install -y libjpeg62-turbo libopenjp2-7 libtiff5 libatlas-base-dev libxcb1 libhdf5-dev

RUN pip install --upgrade pip

COPY ./app/requirements.txt ./
RUN pip install -r requirements.txt --extra-index-url 'https://www.piwheels.org/simple'

WORKDIR /app

COPY ./app/ .

# Expose the port
EXPOSE 80

RUN [ "cross-build-end" ]

CMD [ "python3", "-u", "./app.py" ]
